In [1]:
import math

In [2]:
pow(2,3)

8

# Package

In [ ]:
# Numpy: array
# pandas: Data Frame (timeseries) 
# matplotlib : Data visualization 

In [4]:
import numpy as np 
import pandas as pd 
import matplotlib as plt 

In [11]:
pip install pandas-datareader


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.5/109.5 kB 61.8 kB/s eta 0:00:00a 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [13]:
import pandas_datareader as web


# Numpy Array 

In [14]:
list_1 = [1, 2, 3, 4, 5]


In [15]:
arr_1 = np.array(list_1)
arr_1

array([1, 2, 3, 4, 5])

In [16]:
type(arr_1)

numpy.ndarray

In [18]:
matrix_1 = [[1, 2, 3, 4], [5, 6, 7, 8]]
np.array(matrix_1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# 2 dimentions array 


In [19]:
# Genarate random number 

In [20]:
np.random.random()

0.8410274748611503

In [21]:
np.random.random(5)

array([0.86413275, 0.3184963 , 0.51346419, 0.82053975, 0.16278835])

In [24]:
np.random.randint(0, 10, (2, 2))

array([[7, 7],
       [9, 4]])

In [26]:
np.arange(1, 5, 2)

array([1, 3])

In [28]:
np.ones_like(5)

array(1)

# reshape 

In [30]:
array_2 = np.arange(1, 9)

In [32]:
array_2.shape

(8,)

In [33]:
array_2.reshape((2, 4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
a = array_2.reshape((4, 2))

In [36]:
a.shape

(4, 2)

# Numpy Operations 

In [43]:
array_1 = np.arange(1 , 5)

In [44]:
array_1

array([1, 2, 3, 4])

In [47]:
array_2 = np.arange(5, 9)

In [48]:
array_2

array([5, 6, 7, 8])

In [49]:
array_1 + array_2

array([ 6,  8, 10, 12])

In [ ]:
# if a mount of element both array is diffence some error will apear

In [50]:
array_1 * array_2

array([ 5, 12, 21, 32])

In [53]:

array_1/array_2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

# Numpy Indexing 

In [54]:
array_1 = np.arange(0, 11)

In [55]:
array_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
array_1[2]

2

In [61]:
array_1[:3]

array([0, 1, 2])

In [62]:
# reassign  

In [64]:
array_1[1:5] = 15
array_1

array([ 0, 15, 15, 15, 15,  5,  6,  7,  8,  9, 10])

In [65]:
arr_copy = array_1.copy()

In [68]:
arr_copy[1:4] = 17
arr_copy

array([ 0, 17, 17, 17, 15,  5,  6,  7,  8,  9, 10])

In [70]:
x = np.array([[3, 5, 7], [2, 4, 6]])
x

array([[3, 5, 7],
       [2, 4, 6]])

In [75]:
x[0, 1
 ]

5

In [76]:
x[0][1]

5

In [77]:
x[1][2]

6

# Conditional Indexing 

In [79]:
y = np.arange(2, 20, 3)
y

array([ 2,  5,  8, 11, 14, 17])

In [80]:
cond = y > 5 

In [82]:
y[y>5]

array([ 8, 11, 14, 17])